/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springboot.example.com;

import static org.junit.Assert.*;

import org.junit.Test;

public class ServerMainTest {
    @Test
    public void testAppHasAGreeting() {
        ServerMain classUnderTest = new ServerMain();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
